volumes:
  pollution_backend_local_postgres_data: {}
  pollution_backend_local_postgres_data_backups: {}
  pollution_backend_local_redis_data: {}
  pollution_backend_local_mosquitto_data: {}
  pollution_backend_local_mosquitto_log: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: pollution_backend_local_django
    container_name: pollution_backend_local_django
    depends_on:
      - postgres
      - redis
    volumes:
      - /app/.venv
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  mqtt_listener:
    <<: *django
    container_name: pollution_backend_local_mqtt_listener
    depends_on:
      - postgres
      - redis
      - mosquitto
    ports: []
    command: python manage.py start_mqtt_listener

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: postgis/postgis:15-3.3
    container_name: pollution_backend_local_postgres
    volumes:
      - pollution_backend_local_postgres_data:/var/lib/postgresql/data
      - pollution_backend_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - "5432:5432"

  redis:
    image: docker.io/redis:7.2
    container_name: pollution_backend_local_redis
    volumes:
      - pollution_backend_local_redis_data:/data

  celeryworker:
    <<: *django
    image: pollution_backend_local_celeryworker
    container_name: pollution_backend_local_celeryworker
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: pollution_backend_local_celerybeat
    container_name: pollution_backend_local_celerybeat
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: pollution_backend_local_flower
    container_name: pollution_backend_local_flower
    ports:
      - '5555:5555'
    command: /start-flower

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: pollution_backend_local_mosquitto
    volumes:
      - ./compose/local/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - pollution_backend_local_mosquitto_data:/mosquitto/data
      - pollution_backend_local_mosquitto_log:/mosquitto/log
    ports:
      - '1883:1883'
      - '9001:9001'
